### ISSUE TITLE
Uncaught Error: ERROR: 0:2: '' : No precision specified for (float)

### ISSUE THREAD

**Issue by saldukoo** [skeeto/webgl-game-of-life#1]
Igloo threw this error after shamelessly copying everything.
"Uncaught Error: ERROR: 0:2: '' : No precision specified for (float)"

Fixed by adding these lines to the start of each fragment shader
# ifdef GL_ES

precision mediump float;
# endif

**Comment by skeeto** [comment]
These lines have been in this project's shaders since the beginning. It's essential for all WebGL fragment shaders, so it's hard to miss.
